### ISSUE TITLE
Tensor.SameChars test has non-deterministic outcomes

### ISSUE THREAD

**Issue by ajoudaki** [ratschlab/Project2020-seq-tensor-sketching#29] opened 2021-01-21 09:34 UTC
Outcome of test cases must be deterministic, not dependent on any random device

**Comment by danieldanciu** [comment] 2021-01-21 10:03
I agree that tests should be deterministic.
Here however, I think the problem is not the test, but the TS
implementation. The test is pointing out that TS is returning an unexpected
result.

**Comment by RagnarGrootKoerkamp** [comment] 2021-01-26 11:23
Fixed by https://github.com/ratschlab/Project2020-seq-tensor-sketching/commit/56f962ea3e870f7df011ae275369be9f45afe373: the constructor had the wrong variable passed in

**Closed as completed** 2021-01-26 12:16 UTC
